// Generated by `mcp__Supabase__generate_typescript_types` against the live
// AwardPair project (ykxkyoddeoqaobqufqzm). Regenerate after any schema
// migration rather than hand-editing.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      airports: {
        Row: {
          city: string
          country_code: string
          iata_code: string
          name: string
          time_zone: string
        }
        Insert: {
          city: string
          country_code: string
          iata_code: string
          name: string
          time_zone: string
        }
        Update: {
          city?: string
          country_code?: string
          iata_code?: string
          name?: string
          time_zone?: string
        }
        Relationships: []
      }
      alert_events: {
        Row: {
          alert_id: string
          id: string
          notified_at: string | null
          pair_snapshot: Json
          triggered_at: string
        }
        Insert: {
          alert_id: string
          id?: string
          notified_at?: string | null
          pair_snapshot: Json
          triggered_at?: string
        }
        Update: {
          alert_id?: string
          id?: string
          notified_at?: string | null
          pair_snapshot?: Json
          triggered_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "alert_events_alert_id_fkey"
            columns: ["alert_id"]
            isOneToOne: false
            referencedRelation: "alerts"
            referencedColumns: ["id"]
          },
        ]
      }
      alerts: {
        Row: {
          created_at: string
          criteria: Json
          id: string
          is_active: boolean
          saved_search_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          criteria: Json
          id?: string
          is_active?: boolean
          saved_search_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          criteria?: Json
          id?: string
          is_active?: boolean
          saved_search_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "alerts_saved_search_id_fkey"
            columns: ["saved_search_id"]
            isOneToOne: false
            referencedRelation: "saved_searches"
            referencedColumns: ["id"]
          },
        ]
      }
      award_observations: {
        Row: {
          arrival_at: string
          available_seats: number | null
          cabin: string
          departure_at: string
          destination_airport_code: string
          expires_at: string | null
          flight_number: string | null
          id: string
          layover_airport_codes: string[] | null
          marketing_airline: string
          mileage_program_id: string
          observed_at: string
          operating_airline: string | null
          origin_airport_code: string
          points_cost: number
          provider: string
          stops: number
          taxes_amount: number
          taxes_currency: string
        }
        Insert: {
          arrival_at: string
          available_seats?: number | null
          cabin: string
          departure_at: string
          destination_airport_code: string
          expires_at?: string | null
          flight_number?: string | null
          id?: string
          layover_airport_codes?: string[] | null
          marketing_airline: string
          mileage_program_id: string
          observed_at?: string
          operating_airline?: string | null
          origin_airport_code: string
          points_cost: number
          provider: string
          stops?: number
          taxes_amount: number
          taxes_currency: string
        }
        Update: {
          arrival_at?: string
          available_seats?: number | null
          cabin?: string
          departure_at?: string
          destination_airport_code?: string
          expires_at?: string | null
          flight_number?: string | null
          id?: string
          layover_airport_codes?: string[] | null
          marketing_airline?: string
          mileage_program_id?: string
          observed_at?: string
          operating_airline?: string | null
          origin_airport_code?: string
          points_cost?: number
          provider?: string
          stops?: number
          taxes_amount?: number
          taxes_currency?: string
        }
        Relationships: [
          {
            foreignKeyName: "award_observations_destination_airport_code_fkey"
            columns: ["destination_airport_code"]
            isOneToOne: false
            referencedRelation: "airports"
            referencedColumns: ["iata_code"]
          },
          {
            foreignKeyName: "award_observations_mileage_program_id_fkey"
            columns: ["mileage_program_id"]
            isOneToOne: false
            referencedRelation: "mileage_programs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "award_observations_origin_airport_code_fkey"
            columns: ["origin_airport_code"]
            isOneToOne: false
            referencedRelation: "airports"
            referencedColumns: ["iata_code"]
          },
        ]
      }
      card_benefit_rules: {
        Row: {
          applicable_program_ids: string[] | null
          card_product_id: string
          effective_from: string
          effective_to: string | null
          id: string
          max_amount_currency: string
          max_amount_value: number
          minimum_nights: number | null
          period: string
          requires_booking_channel: string | null
          requires_prepaid_booking: boolean
          source_url: string | null
          type: string
          verified_at: string
        }
        Insert: {
          applicable_program_ids?: string[] | null
          card_product_id: string
          effective_from: string
          effective_to?: string | null
          id?: string
          max_amount_currency: string
          max_amount_value: number
          minimum_nights?: number | null
          period: string
          requires_booking_channel?: string | null
          requires_prepaid_booking?: boolean
          source_url?: string | null
          type: string
          verified_at: string
        }
        Update: {
          applicable_program_ids?: string[] | null
          card_product_id?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          max_amount_currency?: string
          max_amount_value?: number
          minimum_nights?: number | null
          period?: string
          requires_booking_channel?: string | null
          requires_prepaid_booking?: boolean
          source_url?: string | null
          type?: string
          verified_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "card_benefit_rules_card_product_id_fkey"
            columns: ["card_product_id"]
            isOneToOne: false
            referencedRelation: "card_products"
            referencedColumns: ["id"]
          },
        ]
      }
      card_issuers: {
        Row: {
          id: string
          name: string
          slug: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
        }
        Relationships: []
      }
      card_products: {
        Row: {
          id: string
          issuer_id: string
          name: string
          slug: string
        }
        Insert: {
          id?: string
          issuer_id: string
          name: string
          slug: string
        }
        Update: {
          id?: string
          issuer_id?: string
          name?: string
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "card_products_issuer_id_fkey"
            columns: ["issuer_id"]
            isOneToOne: false
            referencedRelation: "card_issuers"
            referencedColumns: ["id"]
          },
        ]
      }
      hotel_offers: {
        Row: {
          additional_credit_amount_currency: string | null
          additional_credit_amount_value: number | null
          blackout_dates: string[] | null
          booking_window_end: string | null
          booking_window_start: string | null
          description: string
          discount_amount_currency: string | null
          discount_amount_value: number | null
          discount_percentage: number | null
          eligible_card_product_ids: string[] | null
          hotel_id: string | null
          id: string
          maximum_nights: number | null
          minimum_nights: number | null
          program_id: string | null
          source_url: string | null
          stay_window_end: string | null
          stay_window_start: string | null
          type: string
          verified_at: string
        }
        Insert: {
          additional_credit_amount_currency?: string | null
          additional_credit_amount_value?: number | null
          blackout_dates?: string[] | null
          booking_window_end?: string | null
          booking_window_start?: string | null
          description: string
          discount_amount_currency?: string | null
          discount_amount_value?: number | null
          discount_percentage?: number | null
          eligible_card_product_ids?: string[] | null
          hotel_id?: string | null
          id?: string
          maximum_nights?: number | null
          minimum_nights?: number | null
          program_id?: string | null
          source_url?: string | null
          stay_window_end?: string | null
          stay_window_start?: string | null
          type: string
          verified_at: string
        }
        Update: {
          additional_credit_amount_currency?: string | null
          additional_credit_amount_value?: number | null
          blackout_dates?: string[] | null
          booking_window_end?: string | null
          booking_window_start?: string | null
          description?: string
          discount_amount_currency?: string | null
          discount_amount_value?: number | null
          discount_percentage?: number | null
          eligible_card_product_ids?: string[] | null
          hotel_id?: string | null
          id?: string
          maximum_nights?: number | null
          minimum_nights?: number | null
          program_id?: string | null
          source_url?: string | null
          stay_window_end?: string | null
          stay_window_start?: string | null
          type?: string
          verified_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "hotel_offers_hotel_id_fkey"
            columns: ["hotel_id"]
            isOneToOne: false
            referencedRelation: "hotels"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hotel_offers_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "hotel_programs"
            referencedColumns: ["id"]
          },
        ]
      }
      hotel_program_benefits: {
        Row: {
          amount_currency: string | null
          amount_value: number | null
          description: string
          effective_from: string
          effective_to: string | null
          id: string
          program_id: string
          source_url: string | null
          type: string
          verified_at: string
        }
        Insert: {
          amount_currency?: string | null
          amount_value?: number | null
          description: string
          effective_from: string
          effective_to?: string | null
          id?: string
          program_id: string
          source_url?: string | null
          type: string
          verified_at: string
        }
        Update: {
          amount_currency?: string | null
          amount_value?: number | null
          description?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          program_id?: string
          source_url?: string | null
          type?: string
          verified_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "hotel_program_benefits_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "hotel_programs"
            referencedColumns: ["id"]
          },
        ]
      }
      hotel_program_memberships: {
        Row: {
          first_seen_at: string
          hotel_id: string
          id: string
          last_verified_at: string
          program_id: string
          source_url: string | null
          valid_from: string
          valid_to: string | null
          verification_method: string
        }
        Insert: {
          first_seen_at?: string
          hotel_id: string
          id?: string
          last_verified_at: string
          program_id: string
          source_url?: string | null
          valid_from: string
          valid_to?: string | null
          verification_method: string
        }
        Update: {
          first_seen_at?: string
          hotel_id?: string
          id?: string
          last_verified_at?: string
          program_id?: string
          source_url?: string | null
          valid_from?: string
          valid_to?: string | null
          verification_method?: string
        }
        Relationships: [
          {
            foreignKeyName: "hotel_program_memberships_hotel_id_fkey"
            columns: ["hotel_id"]
            isOneToOne: false
            referencedRelation: "hotels"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hotel_program_memberships_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "hotel_programs"
            referencedColumns: ["id"]
          },
        ]
      }
      hotel_programs: {
        Row: {
          id: string
          issuer: string
          name: string
          slug: string
        }
        Insert: {
          id?: string
          issuer: string
          name: string
          slug: string
        }
        Update: {
          id?: string
          issuer?: string
          name?: string
          slug?: string
        }
        Relationships: []
      }
      hotel_property_benefits: {
        Row: {
          amount_currency: string | null
          amount_value: number | null
          description: string
          effective_from: string
          effective_to: string | null
          hotel_id: string
          id: string
          overrides_program_benefit_id: string | null
          program_id: string
          source_url: string | null
          type: string
          verified_at: string
        }
        Insert: {
          amount_currency?: string | null
          amount_value?: number | null
          description: string
          effective_from: string
          effective_to?: string | null
          hotel_id: string
          id?: string
          overrides_program_benefit_id?: string | null
          program_id: string
          source_url?: string | null
          type: string
          verified_at: string
        }
        Update: {
          amount_currency?: string | null
          amount_value?: number | null
          description?: string
          effective_from?: string
          effective_to?: string | null
          hotel_id?: string
          id?: string
          overrides_program_benefit_id?: string | null
          program_id?: string
          source_url?: string | null
          type?: string
          verified_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "hotel_property_benefits_hotel_id_fkey"
            columns: ["hotel_id"]
            isOneToOne: false
            referencedRelation: "hotels"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hotel_property_benefits_overrides_program_benefit_id_fkey"
            columns: ["overrides_program_benefit_id"]
            isOneToOne: false
            referencedRelation: "hotel_program_benefits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hotel_property_benefits_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "hotel_programs"
            referencedColumns: ["id"]
          },
        ]
      }
      hotel_rate_nights: {
        Row: {
          id: string
          rate_observation_id: string
          room_rate_amount: number
          room_rate_currency: string
          stay_date: string
        }
        Insert: {
          id?: string
          rate_observation_id: string
          room_rate_amount: number
          room_rate_currency: string
          stay_date: string
        }
        Update: {
          id?: string
          rate_observation_id?: string
          room_rate_amount?: number
          room_rate_currency?: string
          stay_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "hotel_rate_nights_rate_observation_id_fkey"
            columns: ["rate_observation_id"]
            isOneToOne: false
            referencedRelation: "hotel_rate_observations"
            referencedColumns: ["id"]
          },
        ]
      }
      hotel_rate_observations: {
        Row: {
          check_in_date: string
          check_out_date: string
          comparability_dates_match: boolean
          comparability_meal_inclusion_known: boolean
          comparability_occupancy_known: boolean
          comparability_property_match: boolean
          comparability_refundability_known: boolean
          comparability_room_type_known: boolean
          comparability_taxes_and_fees_known: boolean
          confidence_level: string
          confidence_reason: string
          expires_at: string | null
          hotel_id: string
          id: string
          mandatory_fees_amount: number
          mandatory_fees_currency: string
          meal_inclusion: string | null
          observed_at: string
          provenance: string
          refundable: boolean
          taxes_amount: number
          taxes_currency: string
        }
        Insert: {
          check_in_date: string
          check_out_date: string
          comparability_dates_match?: boolean
          comparability_meal_inclusion_known?: boolean
          comparability_occupancy_known?: boolean
          comparability_property_match?: boolean
          comparability_refundability_known?: boolean
          comparability_room_type_known?: boolean
          comparability_taxes_and_fees_known?: boolean
          confidence_level: string
          confidence_reason: string
          expires_at?: string | null
          hotel_id: string
          id?: string
          mandatory_fees_amount: number
          mandatory_fees_currency: string
          meal_inclusion?: string | null
          observed_at?: string
          provenance: string
          refundable?: boolean
          taxes_amount: number
          taxes_currency: string
        }
        Update: {
          check_in_date?: string
          check_out_date?: string
          comparability_dates_match?: boolean
          comparability_meal_inclusion_known?: boolean
          comparability_occupancy_known?: boolean
          comparability_property_match?: boolean
          comparability_refundability_known?: boolean
          comparability_room_type_known?: boolean
          comparability_taxes_and_fees_known?: boolean
          confidence_level?: string
          confidence_reason?: string
          expires_at?: string | null
          hotel_id?: string
          id?: string
          mandatory_fees_amount?: number
          mandatory_fees_currency?: string
          meal_inclusion?: string | null
          observed_at?: string
          provenance?: string
          refundable?: boolean
          taxes_amount?: number
          taxes_currency?: string
        }
        Relationships: [
          {
            foreignKeyName: "hotel_rate_observations_hotel_id_fkey"
            columns: ["hotel_id"]
            isOneToOne: false
            referencedRelation: "hotels"
            referencedColumns: ["id"]
          },
        ]
      }
      hotels: {
        Row: {
          city: string
          country_code: string
          id: string
          latitude: number | null
          longitude: number | null
          name: string
        }
        Insert: {
          city: string
          country_code: string
          id?: string
          latitude?: number | null
          longitude?: number | null
          name: string
        }
        Update: {
          city?: string
          country_code?: string
          id?: string
          latitude?: number | null
          longitude?: number | null
          name?: string
        }
        Relationships: []
      }
      mileage_programs: {
        Row: {
          id: string
          name: string
          slug: string
          transferable_from: string[] | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          transferable_from?: string[] | null
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          transferable_from?: string[] | null
        }
        Relationships: []
      }
      saved_searches: {
        Row: {
          created_at: string
          id: string
          name: string
          params: Json
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          params: Json
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          params?: Json
          user_id?: string
        }
        Relationships: []
      }
      transfer_relationships: {
        Row: {
          effective_from: string
          effective_to: string | null
          id: string
          mileage_program_id: string
          ratio_denominator: number
          ratio_numerator: number
          source_url: string | null
          transferable_program_id: string
          verified_at: string
        }
        Insert: {
          effective_from: string
          effective_to?: string | null
          id?: string
          mileage_program_id: string
          ratio_denominator: number
          ratio_numerator: number
          source_url?: string | null
          transferable_program_id: string
          verified_at: string
        }
        Update: {
          effective_from?: string
          effective_to?: string | null
          id?: string
          mileage_program_id?: string
          ratio_denominator?: number
          ratio_numerator?: number
          source_url?: string | null
          transferable_program_id?: string
          verified_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "transfer_relationships_mileage_program_id_fkey"
            columns: ["mileage_program_id"]
            isOneToOne: false
            referencedRelation: "mileage_programs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transfer_relationships_transferable_program_id_fkey"
            columns: ["transferable_program_id"]
            isOneToOne: false
            referencedRelation: "transferable_programs"
            referencedColumns: ["id"]
          },
        ]
      }
      transferable_programs: {
        Row: {
          id: string
          name: string
          slug: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
        }
        Relationships: []
      }
      user_benefit_preferences: {
        Row: {
          breakfast_value_amount: number
          breakfast_value_currency: string
          late_checkout_value_amount: number | null
          late_checkout_value_currency: string | null
          property_credit_usable_fraction: number
          user_id: string
        }
        Insert: {
          breakfast_value_amount?: number
          breakfast_value_currency?: string
          late_checkout_value_amount?: number | null
          late_checkout_value_currency?: string | null
          property_credit_usable_fraction?: number
          user_id: string
        }
        Update: {
          breakfast_value_amount?: number
          breakfast_value_currency?: string
          late_checkout_value_amount?: number | null
          late_checkout_value_currency?: string | null
          property_credit_usable_fraction?: number
          user_id?: string
        }
        Relationships: []
      }
      user_cards: {
        Row: {
          added_at: string
          card_product_id: string
          credit_used_amount: number | null
          credit_used_currency: string | null
          id: string
          user_id: string
        }
        Insert: {
          added_at?: string
          card_product_id: string
          credit_used_amount?: number | null
          credit_used_currency?: string | null
          id?: string
          user_id: string
        }
        Update: {
          added_at?: string
          card_product_id?: string
          credit_used_amount?: number | null
          credit_used_currency?: string | null
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_cards_card_product_id_fkey"
            columns: ["card_product_id"]
            isOneToOne: false
            referencedRelation: "card_products"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          created_at: string
          id: string
        }
        Insert: {
          created_at?: string
          id: string
        }
        Update: {
          created_at?: string
          id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
